#!/bin/sh

. ./helpers.sh

Main() {
  SetAppFile
  SetAppPath
  SetAppName
  [ $# -eq 0 ] && ExitHelp 1

  case "$1" in
  --debug)      log_level='debug' ;;
  -h|--help)    ExitHelp          ;;
  -V|--version) ExitVersion       ;;
  -v|--verbose) SetVerbose; shift ;;
  esac

  SetPackageManager
  SetSudo
  "$package_manager" "$@"
}

# plugins are named `upm-<any_pkg_mgr_executible>`
# TODO: support multiple package managers, ex. apt-get, aptitude, apt
# TODO: support non-OS package managers, ex. gem and npm
SetPackageManager() {
  for file in $(find "$app_path" -maxdepth 1 -type f -name "$app_name-*"); do
    plugin=${file#$app_file-}
    if IsCommand "$plugin"; then
      package_manager="$plugin"
      break
    fi
  done

  [ -z "$package_manager" ] && ExitError 'Cannot find a known Package Manager.'
  [ -n "$verbose" ] && LogInfo "Detected '$package_manager' package manager"
}

Main "$@"
