#!/bin/sh

PmHelp() {
	PrintHeader 'xbps-query'
	xbps-query   --help
	PrintHeader 'xbps-install'
	xbps-install --help
	PrintHeader 'xbps-remove'
	xbps-remove  --help
}

RepoAdd() {
	[ -z "$1" ] && ExitMissingArgs '<repo>'

	ExitNotImplemented "$object $action"
}

RepoRemove() {
	[ -z "$1" ] && ExitMissingArgs '<repo>'

	ExitNotImplemented "$object $action"
}
RepoEnable() {
	[ -z "$1" ] && ExitMissingArgs '<repo>'

	ExitNotImplemented "$object $action"
}

RepoDisable() {
	[ -z "$1" ] && ExitMissingArgs '<repo>'

	ExitNotImplemented "$object $action"
}

RepoListAll() {
	xbps-query --repository --search 'void-repo'
}

RepoListEnabled() {
	xbps-query --list-repos
}

RepoListDisabled() {
	ExitNotImplemented "$object $action $option"
}

DbRefresh() {
	$SUDO xbps-install --sync
}

PkgFind() {
	xbps-query --repository --search "$@"
}

PkgInfo() {
	PkgShow "$@" \
		| grep -vE '^[aflmr]|^so' \
		| grep -E --color=always '^[^:]*[:[:space:]]'
}

PkgShow() {
	xbps-query -RS "$@"
}

PkgInstall() {
	$SUDO xbps-install "$@"
}

PkgUninstall() {
	$SUDO xbps-remove "$@"
}

PkgLock() {
	xbps-pkgdb -mode 'hold' "$@"
}

PkgUnlock() {
	xbps-pkgdb -mode 'unhold' "$@"
}

PkgSetManual() {
	xbps-pkgdb -mode 'manual' "$@"
}

PkgSetAuto() {
	xbps-pkgdb -mode 'auto' "$@"
}

PkgListAll()     {
	xbps-query --list-pkgs
}

PkgListLocked()  {
	xbps-query --list-hold-pkgs
}

PkgListManual()  {
	xbps-query --list-manual-pkgs
}

PkgListOrphans() {
	xbps-query --list-orphans
}

PkgUpgrade() {
	$SUDO xbps-install --sync --update "$@"
}

PkgUpdate() {
	ExitNotImplemented "$object $action"
}

Unknown() {
	xbps-$*
}
