#!/bin/sh

main() {
  case "$1" in
    find)    shift; xbps-query --repository --search "$@" ;;
    info)    shift; info ;;
    show)    shift; xbps-query -RS "$@" ;;
    lock)    set "$@" ;;
    unlock)  set "$@" ;;
    set)     shift; set "$@" ;;
    list)    shift; package_list "$@" ;;
    locked)  package_list "$@" ;;
    orphans) package_list "$@" ;;
    manual)  package_list "$@" ;;
    repos)   shift; repo 'list' "$@" ;;
    upgrade) shift; $SUDO xbps-install --sync --update "$@" ;;
    update)  shift; echo "TODO" ;;
    repo)    shift; repo "$@" ;;
    repos)   shift; repo 'list' "$@" ;;
    refresh) $SUDO xbps-install --sync ;;
    *)       $SUDO sh -c "xbps-$*" ;;
  esac
}

info() {
  xbps-query --repository --search "$@" \
    | grep -vE '^[aflmr]|^so' \
    | grep -E --color=always '^[^:]*[:[:space:]]'
}

set() {
  case "$1" in
    lock)   xbps-pkgdb -mode 'hold' ;;
    unlock) xbps-pkgdb -mode 'unhold' ;;
    manual) xbps-pkgdb -mode 'manual' ;;
    auto)   xbps-pkgdb -mode 'auto' ;;
    *) exitError "Unknown package set option '$@'" ;;
  esac
}

package_list() {
  if [ $# -eq 0 ]; then
    option='all'
  else
    option="$1"
    shift
  fi

  case "$option" in
    all)     xbps-query --list-pkgs ;;
    locked)  xbps-query --list-hold-pkgs ;;
    manual)  xbps-query --list-manual-pkgs ;;
    orphans) xbps-query --list-orphans ;;
    *) exitError "Unknown package list option '$@'" ;;
  esac
}

repo() {
  case "$1" in
    add)     echo TODO ;;
    remove)  echo TODO ;;
    enable)  echo TODO ;;
    disable) echo TODO ;;
    list)    shift; repo_list "$@" ;;
    *) exitError "Unknown repo option '$@'" ;;
  esac
}

repo_list() {
  if [ $# -eq 0 ]; then
    option='enabled'
  else
    option="$1"
    shift
  fi

  case "$option" in
    all)      xbps-query --repository --search void-repo ;;
    enabled)  xbps-query --list-repos ;;
    disabled) echo TODO ;;
    *) exitError "Unknown repo list option '$@'" ;;
  esac
}

main "$@"
